name: barbershop_booking
description: "Modern barbershop booking application with Flutter"
publish_to: 'none'

version: 1.0.0+1

# Project links
homepage: https://github.com/prassaaa/barbershop_booking
repository: https://github.com/prassaaa/barbershop_booking
issue_tracker: https://github.com/prassaaa/barbershop_booking/issues

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  
  # State Management
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.5.6
  
  # Authentication
  google_sign_in: ^6.2.1
  
  # Navigation
  go_router: ^12.1.3
  
  # Local Notifications
  flutter_local_notifications: ^16.3.2
  
  # Date & Time
  intl: ^0.19.0
  table_calendar: ^3.0.9
  timezone: ^0.9.4
  
  # Charts & Graphs
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^24.1.41
  
  # PDF & Excel Export
  pdf: ^3.10.7
  syncfusion_flutter_xlsio: ^24.1.41
  printing: ^5.11.1
  
  # Image Handling
  image_picker: ^1.0.7
  
  # Utilities
  uuid: ^4.3.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  
  # HTTP & Network
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Platform Detection
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700